name: Builder

on:
  push:
    branches:
      - master

env:
  CMAKE_VERSION: 3.25.2
  LLVM_VERSION: 15.0.6
  NDK_VERSION: r25b

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update Ubuntu
      run: |
        sudo apt-get upgrade
        sudo apt-get install -y build-essential tree

    - name: Compile for Android
      run: sh scripts/setup_linux_cross_compile.sh
    - name: Run Python Script
      run: python3 scripts/platform_builder.py --platform=android --arch=all --cmake_dir=$HOME/opt/cmake-3.25.2 --llvm_dir=$HOME/opt/llvm-15.0.6 --android_ndk_dir=$HOME/opt/ndk-r25b

    - name: Run Tree command
      run: tree
      continue-on-error: true

    - name: Upload 1
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: /build
      continue-on-error: true
 
    - name: Upload 2
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: build
      continue-on-error: true

    - name: Tar
      run: tar -cvf build.tar /build
      continue-on-error: true

    - name: Upload 3
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: build.tar
      continue-on-error: true
